Web/Models/Espetaculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AgileTickets.Web.Models
{
    public class Espetaculo
    {
        // propriedades
        public virtual int Id { get; set; }
        public virtual string Nome { get; set; }
        public virtual string Descricao { get; set; }
        public virtual IList<Sessao> Sessoes { get; set; }
        public virtual Estabelecimento Estabelecimento { get; set; }

        public Espetaculo()
        {
            this.Sessoes = new List<Sessao>();
        }
        /*
         * Esse metodo eh responsavel por criar sessoes para
         * o respectivo espetaculo, dado o intervalo de inicio e fim,
         * mais a periodicidade.
         * 
         * O algoritmo funciona da seguinte forma:
         * - Caso a data de inicio seja 01/01/2010, a data de fim seja 03/01/2010,
         * e a periodicidade seja DIARIA, o algoritmo cria 3 sessoes, uma 
         * para cada dia: 01/01, 02/01 e 03/01.
         * 
         * - Caso a data de inicio seja 01/01/2010, a data fim seja 31/01/2010,
         * e a periodicidade seja SEMANAL, o algoritmo cria 5 sessoes, uma
         * a cada 7 dias: 01/01, 08/01, 15/01, 22/01 e 29/01.
         * 
         * Repare que a data da primeira sessao é sempre a data inicial.
         */
        public virtual IList<Sessao> CriaSessoes(DateTime inicio, DateTime fim, Periodicidade periodicidade)
        {
            // ALUNO: Não apague esse metodo. Esse sim será usado no futuro! ;)
            return null;
        }

        public virtual bool Vagas(int qtd, int min)
        {
            // ALUNO: Não apague esse metodo. Esse sim será usado no futuro! ;)
            int totDisp = 0;

            foreach (Sessao s in Sessoes)
            {
                if (s.IngressosDisponiveis < min) return false;
                totDisp += s.IngressosDisponiveis;
            }

            if (totDisp >= qtd) return true;
            else return false;
        }

        public virtual bool Vagas(int qtd)
        {
            // ALUNO: Não apague esse metodo. Esse sim será usado no futuro! ;)
            int totDisp = 0;

            foreach (Sessao s in Sessoes)
            {
                totDisp += s.IngressosDisponiveis;
            }

            if (totDisp >= qtd) return true;
            else return false;
        }
    }
}

Web/Controllers/EspetaculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgileTickets.Web.Repositorios;
using AgileTickets.Web.Models;
using AgileTickets.Web.Infra.Database;

namespace AgileTickets.Web.Controllers
{
    public class EspetaculosController : Controller
    {
        private Agenda agenda;
        private DiretorioDeEstabelecimentos estabelecimentos;

        public EspetaculosController(Agenda agenda, DiretorioDeEstabelecimentos estabelecimentos)
        {
            this.agenda = agenda;
            this.estabelecimentos = estabelecimentos;
        }

        public ActionResult Index()
        {
            string titulo = "Todos os espetaculos";

            ViewBag.Estabelecimentos = estabelecimentos.Todos();
            return View(agenda.Espetaculos());
        }

        [RequiresTransaction]
        public ActionResult Novo(Espetaculo espetaculo) {
            agenda.Cadastra(espetaculo);

            return RedirectToAction("Index");
        }

        private ActionResult VoltaPraIndex()
        {
            return RedirectToAction("Index");
        }

    }
}

Web/Views/Espetaculos/Index.cshtml
@model IList<AgileTickets.Web.Models.Espetaculo>
@{
    ViewBag.Title = "Espetáculos";
}

<h2>Espetáculos</h2>

<form action="@Url.Action("Novo", "Espetaculos")" method="post">
Nome: <input type="text" name="espetaculo.nome" />
Descrição: <input type="text" name="espetaculo.descricao" />
Estabelecimento: 
<select name="espetaculo.estabelecimento.id">
    @foreach(var item in ViewBag.Estabelecimentos) {
        <option value="@item.Id">@item.Nome</option>
    }
</select>
<input type="submit" value="Adicionar" />
</form>

<table width="100%">

    <tr>
        <td width="30%">Nome</td>
        <td width="30%">Descrição</td>
        <td width="25%">Estabelecimento</td>
        <td width="15%"></td>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Descricao</td>
            <td>@item.Estabelecimento.Nome</td>
            <td><a href="@Url.Action("Criar", "Sessoes", new { id = @item.Id})">Criar Sessões</a></td>
        </tr>
    }
</table>